name: reinvent4
channels:
  - conda-forge
  - pytorch
  - rdkit
dependencies:
  - python=3.9
  - pytorch>=1.12.0
  - rdkit>=2022.03.1
  - numpy
  - pandas
  - scipy
  - matplotlib
  - jupyter
  - tqdm
  - pip
  - pip:
    - reinvent4
